//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Virtual8086_Console {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class default_set : global::System.Configuration.ApplicationSettingsBase {
        
        private static default_set defaultInstance = ((default_set)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new default_set())));
        
        public static default_set Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowAssemblerCode {
            get {
                return ((bool)(this["ShowAssemblerCode"]));
            }
            set {
                this["ShowAssemblerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_code.lst")]
        public string Debug_Code_Filename {
            get {
                return ((string)(this["Debug_Code_Filename"]));
            }
            set {
                this["Debug_Code_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_ports.lst")]
        public string Debug_Ports_Filename {
            get {
                return ((string)(this["Debug_Ports_Filename"]));
            }
            set {
                this["Debug_Ports_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveAssemblerCode {
            get {
                return ((bool)(this["SaveAssemblerCode"]));
            }
            set {
                this["SaveAssemblerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveDebugPorts {
            get {
                return ((bool)(this["SaveDebugPorts"]));
            }
            set {
                this["SaveDebugPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveDebugMemory {
            get {
                return ((bool)(this["SaveDebugMemory"]));
            }
            set {
                this["SaveDebugMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayBIOSWhenDebugging {
            get {
                return ((bool)(this["DisplayBIOSWhenDebugging"]));
            }
            set {
                this["DisplayBIOSWhenDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisplayVGABIOSWhenDebugging {
            get {
                return ((bool)(this["DisplayVGABIOSWhenDebugging"]));
            }
            set {
                this["DisplayVGABIOSWhenDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint DebugAtSegment {
            get {
                return ((uint)(this["DebugAtSegment"]));
            }
            set {
                this["DebugAtSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1048576")]
        public uint DebugAtAddress {
            get {
                return ((uint)(this["DebugAtAddress"]));
            }
            set {
                this["DebugAtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3180")]
        public uint DieAtSegment {
            get {
                return ((uint)(this["DieAtSegment"]));
            }
            set {
                this["DieAtSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugAtEnabled {
            get {
                return ((bool)(this["DebugAtEnabled"]));
            }
            set {
                this["DebugAtEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DieAtEnabled {
            get {
                return ((bool)(this["DieAtEnabled"]));
            }
            set {
                this["DieAtEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("i80386")]
        public global::VirtualProcessor.eProcTypes ProcessorType {
            get {
                return ((global::VirtualProcessor.eProcTypes)(this["ProcessorType"]));
            }
            set {
                this["ProcessorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FD2PathAndFile {
            get {
                return ((string)(this["FD2PathAndFile"]));
            }
            set {
                this["FD2PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("306")]
        public uint HD1Cyls {
            get {
                return ((uint)(this["HD1Cyls"]));
            }
            set {
                this["HD1Cyls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint HD2Cyls {
            get {
                return ((uint)(this["HD2Cyls"]));
            }
            set {
                this["HD2Cyls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public uint HD1Heads {
            get {
                return ((uint)(this["HD1Heads"]));
            }
            set {
                this["HD1Heads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint HD2Heads {
            get {
                return ((uint)(this["HD2Heads"]));
            }
            set {
                this["HD2Heads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public uint HD1SPT {
            get {
                return ((uint)(this["HD1SPT"]));
            }
            set {
                this["HD1SPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public uint HD2SPT {
            get {
                return ((uint)(this["HD2SPT"]));
            }
            set {
                this["HD2SPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IDE_DISK")]
        public global::VirtualProcessor.Devices.device_type_t HD1DeviceType {
            get {
                return ((global::VirtualProcessor.Devices.device_type_t)(this["HD1DeviceType"]));
            }
            set {
                this["HD1DeviceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::VirtualProcessor.Devices.device_type_t HD2DeviceType {
            get {
                return ((global::VirtualProcessor.Devices.device_type_t)(this["HD2DeviceType"]));
            }
            set {
                this["HD2DeviceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartOnLoad {
            get {
                return ((bool)(this["StartOnLoad"]));
            }
            set {
                this["StartOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TimerTickInterval {
            get {
                return ((int)(this["TimerTickInterval"]));
            }
            set {
                this["TimerTickInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MiscROMPathAndFile {
            get {
                return ((string)(this["MiscROMPathAndFile"]));
            }
            set {
                this["MiscROMPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MiscROMLoadAddress {
            get {
                return ((int)(this["MiscROMLoadAddress"]));
            }
            set {
                this["MiscROMLoadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartEmuOnLoad {
            get {
                return ((bool)(this["StartEmuOnLoad"]));
            }
            set {
                this["StartEmuOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DumpMemOnShutdown {
            get {
                return ((bool)(this["DumpMemOnShutdown"]));
            }
            set {
                this["DumpMemOnShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DumpMemAbove1MB {
            get {
                return ((bool)(this["DumpMemAbove1MB"]));
            }
            set {
                this["DumpMemAbove1MB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DumpMemFilename {
            get {
                return ((string)(this["DumpMemFilename"]));
            }
            set {
                this["DumpMemFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_mem.lst")]
        public string Debug_Mem_Filename {
            get {
                return ((string)(this["Debug_Mem_Filename"]));
            }
            set {
                this["Debug_Mem_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugToFile {
            get {
                return ((bool)(this["DebugToFile"]));
            }
            set {
                this["DebugToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugToScreen {
            get {
                return ((bool)(this["DebugToScreen"]));
            }
            set {
                this["DebugToScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CalculateTimings {
            get {
                return ((bool)(this["CalculateTimings"]));
            }
            set {
                this["CalculateTimings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("536870912")]
        public int DebugCodeMaxFileSize {
            get {
                return ((int)(this["DebugCodeMaxFileSize"]));
            }
            set {
                this["DebugCodeMaxFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("818")]
        public uint DieAtAddress {
            get {
                return ((uint)(this["DieAtAddress"]));
            }
            set {
                this["DieAtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6291456")]
        public int PhysicalMemoryAmount {
            get {
                return ((int)(this["PhysicalMemoryAmount"]));
            }
            set {
                this["PhysicalMemoryAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\Emulator Stuff\\from_flash_ubuntu\\v86media\\622c_2.flp")]
        public string FD1PathAndFile {
            get {
                return ((string)(this["FD1PathAndFile"]));
            }
            set {
                this["FD1PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Emulator Stuff\\from_flash_ubuntu\\v86media\\hd10meg3.img")]
        public string HD1PathAndFile {
            get {
                return ((string)(this["HD1PathAndFile"]));
            }
            set {
                this["HD1PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HD2PathAndFile {
            get {
                return ((string)(this["HD2PathAndFile"]));
            }
            set {
                this["HD2PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Emulator Stuff\\bios\\BIOS-bochs-legacy-1hdc")]
        public string BIOSPathAndFile {
            get {
                return ((string)(this["BIOSPathAndFile"]));
            }
            set {
                this["BIOSPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Emulator Stuff\\bios\\VGABIOS-lgpl-latest")]
        public string VideoBiosPathAndFile {
            get {
                return ((string)(this["VideoBiosPathAndFile"]));
            }
            set {
                this["VideoBiosPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("j:\\temp\\Virtual8086_dbg\\")]
        public string Debug_Path {
            get {
                return ((string)(this["Debug_Path"]));
            }
            set {
                this["Debug_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Yogi\\src\\Virtual8086\\cmos.bin")]
        public string CMOSPathAndFile {
            get {
                return ((string)(this["CMOSPathAndFile"]));
            }
            set {
                this["CMOSPathAndFile"] = value;
            }
        }
    }
}
