//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string Test {
            get {
                return ((string)(this["Test"]));
            }
            set {
                this["Test"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string ShowAssemblerCode {
            get {
                return ((string)(this["ShowAssemblerCode"]));
            }
            set {
                this["ShowAssemblerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_code.lst")]
        public string Debug_Code_Filename {
            get {
                return ((string)(this["Debug_Code_Filename"]));
            }
            set {
                this["Debug_Code_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_ports.lst")]
        public string Debug_Ports_Filename {
            get {
                return ((string)(this["Debug_Ports_Filename"]));
            }
            set {
                this["Debug_Ports_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string SaveAssemblerCode {
            get {
                return ((string)(this["SaveAssemblerCode"]));
            }
            set {
                this["SaveAssemblerCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string SaveDebugPorts {
            get {
                return ((string)(this["SaveDebugPorts"]));
            }
            set {
                this["SaveDebugPorts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string SaveDebugMemory {
            get {
                return ((string)(this["SaveDebugMemory"]));
            }
            set {
                this["SaveDebugMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DisplayBIOSWhenDebugging {
            get {
                return ((string)(this["DisplayBIOSWhenDebugging"]));
            }
            set {
                this["DisplayBIOSWhenDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string DisplayVGABIOSWhenDebugging {
            get {
                return ((string)(this["DisplayVGABIOSWhenDebugging"]));
            }
            set {
                this["DisplayVGABIOSWhenDebugging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string DebugAtSegment {
            get {
                return ((string)(this["DebugAtSegment"]));
            }
            set {
                this["DebugAtSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("31744")]
        public string DebugAtAddress {
            get {
                return ((string)(this["DebugAtAddress"]));
            }
            set {
                this["DebugAtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3180")]
        public string DieAtSegment {
            get {
                return ((string)(this["DieAtSegment"]));
            }
            set {
                this["DieAtSegment"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DebugAtEnabled {
            get {
                return ((string)(this["DebugAtEnabled"]));
            }
            set {
                this["DebugAtEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string DieAtEnabled {
            get {
                return ((string)(this["DieAtEnabled"]));
            }
            set {
                this["DieAtEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FD2PathAndFile {
            get {
                return ((string)(this["FD2PathAndFile"]));
            }
            set {
                this["FD2PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("306")]
        public string HD1Cyls {
            get {
                return ((string)(this["HD1Cyls"]));
            }
            set {
                this["HD1Cyls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1015")]
        public string HD2Cyls {
            get {
                return ((string)(this["HD2Cyls"]));
            }
            set {
                this["HD2Cyls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public string HD1Heads {
            get {
                return ((string)(this["HD1Heads"]));
            }
            set {
                this["HD1Heads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public string HD2Heads {
            get {
                return ((string)(this["HD2Heads"]));
            }
            set {
                this["HD2Heads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public string HD1SPT {
            get {
                return ((string)(this["HD1SPT"]));
            }
            set {
                this["HD1SPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("63")]
        public string HD2SPT {
            get {
                return ((string)(this["HD2SPT"]));
            }
            set {
                this["HD2SPT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("52")]
        public string TimerTickInterval {
            get {
                return ((string)(this["TimerTickInterval"]));
            }
            set {
                this["TimerTickInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MiscROMPathAndFile {
            get {
                return ((string)(this["MiscROMPathAndFile"]));
            }
            set {
                this["MiscROMPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string MiscROMLoadAddress {
            get {
                return ((string)(this["MiscROMLoadAddress"]));
            }
            set {
                this["MiscROMLoadAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string StartEmuOnLoad {
            get {
                return ((string)(this["StartEmuOnLoad"]));
            }
            set {
                this["StartEmuOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DumpMemOnShutdown {
            get {
                return ((string)(this["DumpMemOnShutdown"]));
            }
            set {
                this["DumpMemOnShutdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DumpMemAbove1MB {
            get {
                return ((string)(this["DumpMemAbove1MB"]));
            }
            set {
                this["DumpMemAbove1MB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DumpMemFilename {
            get {
                return ((string)(this["DumpMemFilename"]));
            }
            set {
                this["DumpMemFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dbg_mem.lst")]
        public string Debug_Mem_Filename {
            get {
                return ((string)(this["Debug_Mem_Filename"]));
            }
            set {
                this["Debug_Mem_Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string DebugToFile {
            get {
                return ((string)(this["DebugToFile"]));
            }
            set {
                this["DebugToFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string DebugToScreen {
            get {
                return ((string)(this["DebugToScreen"]));
            }
            set {
                this["DebugToScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string CalculateTimings {
            get {
                return ((string)(this["CalculateTimings"]));
            }
            set {
                this["CalculateTimings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("536870912")]
        public string DebugCodeMaxFileSize {
            get {
                return ((string)(this["DebugCodeMaxFileSize"]));
            }
            set {
                this["DebugCodeMaxFileSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("818")]
        public string DieAtAddress {
            get {
                return ((string)(this["DieAtAddress"]));
            }
            set {
                this["DieAtAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000000")]
        public string PhysicalMemoryAmount {
            get {
                return ((string)(this["PhysicalMemoryAmount"]));
            }
            set {
                this["PhysicalMemoryAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h:\\Emulator Stuff\\from_flash_ubuntu\\v86media\\622C_2.flp")]
        public string FD1PathAndFile {
            get {
                return ((string)(this["FD1PathAndFile"]));
            }
            set {
                this["FD1PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h:\\Emulator Stuff\\from_flash_ubuntu\\v86media\\hd10meg3.img")]
        public string HD1PathAndFile {
            get {
                return ((string)(this["HD1PathAndFile"]));
            }
            set {
                this["HD1PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h:\\freedos.img")]
        public string HD2PathAndFile {
            get {
                return ((string)(this["HD2PathAndFile"]));
            }
            set {
                this["HD2PathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Yogi\\src\\bochs-2.6.2\\bios\\BIOS-bochs-legacy")]
        public string BIOSPathAndFile {
            get {
                return ((string)(this["BIOSPathAndFile"]));
            }
            set {
                this["BIOSPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Emulator Stuff\\bios\\VGABIOS-lgpl-latest")]
        public string VideoBiosPathAndFile {
            get {
                return ((string)(this["VideoBiosPathAndFile"]));
            }
            set {
                this["VideoBiosPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("J:\\Yogi\\src\\Virtual8086\\cmos.bin")]
        public string CMOSPathAndFile {
            get {
                return ((string)(this["CMOSPathAndFile"]));
            }
            set {
                this["CMOSPathAndFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string FD1Inserted {
            get {
                return ((string)(this["FD1Inserted"]));
            }
            set {
                this["FD1Inserted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string FD2Inserted {
            get {
                return ((string)(this["FD2Inserted"]));
            }
            set {
                this["FD2Inserted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public string HD1Installed {
            get {
                return ((string)(this["HD1Installed"]));
            }
            set {
                this["HD1Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public string HD2Installed {
            get {
                return ((string)(this["HD2Installed"]));
            }
            set {
                this["HD2Installed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Floppy")]
        public string BootDevice {
            get {
                return ((string)(this["BootDevice"]));
            }
            set {
                this["BootDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\temp\\Virtual8086_dbg\\")]
        public string Debug_Path {
            get {
                return ((string)(this["Debug_Path"]));
            }
            set {
                this["Debug_Path"] = value;
            }
        }
    }
}
